name: EBAC CI

on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest      
    steps:
      # 1) Puxa o código
      - uses: actions/checkout@v4

      # 2) Seta o Node.js e cacheia o npm
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      # 3) Roda o Cypress headless
      - name: Run Cypress e2e tests
        run: npx cypress run
        env:
          CYPRESS_BaseUrl: https://lojajabac.ebaconline.art.br
