name: EBAC CI

on:
  push:
    branches: [ main ]          # troque para o nome da sua branch principal
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
      

    steps:
      # 1) Puxa o código
      - uses: actions/checkout@v4

      # 2) Seta o Node.js e cacheia o npm
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm


      # 3) Instala as deps exatas do package-lock.json
      - name: Install dependencies
        run: npm ci
        env:
          NODE_OPTIONS: "--dns-result-order=ipv4first"

      # 4) Sobe seu servidor estático ou backend
      - name: Start server
        run: npm run start &

      # 5) Aguarda o servidor ficar disponível na porta 3000
      - name: Wait for server to be ready
        uses: iFaxity/wait-on-action@v1.2.1
        with:
          resource: http://localhost:3000
          timeout: 60000

      # 6) Roda o Cypress headless
      - name: Run Cypress e2e tests
        run: npm run test:e2e
